### PR TITLE
Style the front-end mocking generator with CSS

### PR DESCRIPTION
**Pull request by Maluscat**
The title says it all, I applied CSS to the generator to make it a bit more appealing to the eyes

### CODE REVIEW

**Comment by Friz64** [comment]
image
I don't think it's supposed to look like this, could you fix that up?

**Comment by DasEtwas** [comment]
lol fgt

**Comment by Maluscat** [comment]
@Friz64: Fixed it in https://github.com/Friz64/mockingbob-web/pull/1/commits/d418d12b843e87040df0ae0c0f82f739482ce1ad!

**Comment by Friz64** [comment]
image

**Comment by Maluscat** [comment]
👍

**Pull request merged**
